[package]
name = "advent2020"
version = "0.1.0"
authors = ["Xcode23 <joaofarinha10@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
num = "*"
regex = "*"
bincode = "*"
ndarray = "*"
